services:
  backend:
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    volumes: 
      - ./backend:/backend
    command: > 
      bash -c "pip install -r requirements.txt &&  python main.py"


  frontend:
    restart: always
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    command: > 
      bash -c "cp -rfu /temp/node_modules/. /frontend/node_modules/  
      && npm run dev"
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
       